### PR TITLE
Add headers to provider

### PR DESCRIPTION
**Pull request by Mongey**

### CODE REVIEW

**Comment by Mongey** [comment]
I think I probably meant to add tests/docs, and then forgot to follow back up 😅

**Comment by cgbaker** [comment]
@Mongey , i don't mind picking this up and adding tests/docs.

**Comment by cgbaker** [comment]
thanks for the pr, @Mongey ; i've added some tests and documentation.

**Review by jrasell — DISMISSED** [review]
LGTM although I am not sure what is causing the CI failure. I believe `go mod tidy` could be run to clean out some entries in the sum file, but this isn't critical.

**Comment by cgbaker** [comment]
i broke something in `main.go` when i change one of the returns, fixing it now

**Pull request merged**
