### PR TITLE
Support HCL2 on nomad Go package

### PR DESCRIPTION
**Pull request by thiagonache**
Fix https://github.com/hashicorp/terraform-provider-nomad/issues/179

### CODE REVIEW

**Comment by lgfa29** [comment]
Thanks so much for the PR @thiagonache!

It's good to see the tests passing now 🙂

Since the HCL2 jobspec parser is still not 100% compatible with the previous one, I think it would be better to have a config flag that could be set to indicate that the HCL2 parser should be used. 

Something like this:

```hcl
resource "nomad_job" "example" {
  jobspec = "..."
  hcl2 = true
}
```

This config would default to `false` to maintain backwards compatibility with existing Terraform files.

Let me know of you have any questions.

**Comment by thiagonache** [comment]
@lgfa29 Please, let me know if that's okay.

**Review by lgfa29 — APPROVED** [review]
LGTM 👍 

Thank you for the contribution!

**Comment by thiagonache** [comment]
just curious, what's the release cadence of the provider?

**Comment by lgfa29** [comment]
> just curious, what's the release cadence of the provider?

We don't have any specific cadence, it's usually driven by demand or if there is any critical bug fix.

Are you waiting on this feature? There are a few other PRs that should be merged soon, so we will probably cut a release in the coming days.

**Comment by thiagonache** [comment]
That’s good enough. I can use my own build for couple days.

🤩

**Comment by lgfa29** [comment]
FYI @thiagonache,

Turns out that loading local files in HCL2 is a bit tricky, so we changed how the `hcl2` parameter is specified in #192. 

Since your PR has not been released yet, this change won't be listed as a breaking change in our CHANGELOG, but if you are using a custom build you will need to update your Terraform config files.

**Comment by thiagonache** [comment]
thx for letting me know!!!

**Pull request merged**
