### PR TITLE
allow HCL2 file system functions

### LINKED ISSUE #191: Support HCL2 `file` function in jobspec
### Terraform Version
```
Terraform v0.14.4
+ provider hashicorp.com/dev/nomad v0.14.2
```

### Nomad Version
```
Name                          Address    Port  Status  Leader  Protocol  Build  Datacenter  Region
laoqui-hc-mbp-6.local.global  127.0.0.1  4648  alive   true    2         1.0.1  dc1         global
```

### Provider Configuration
```hcl
provider "nomad" {
  address = "http://localhost:4646"
}
```

### Environment Variables
No

### Affected Resource(s)
- `nomad_job`

#### `main.tf`
```hcl
provider "nomad" {
  address = "http://localhost:4646"
}

resource "nomad_job" "nginx" {
  jobspec = file("${path.root}/nginx.nomad")
  hcl2    = true
}
```

#### `nginx.nomad`
```hcl
job "nginx" {
  datacenters = ["dc1"]

  group "nginx" {
    network {
      port "http" {
        to     = 8080
        static = 8080
      }
    }

    task "nginx" {
      driver = "docker"

      config {
        image = "nginx:1.19"
        ports = ["http"]
        volumes = [
          "local/nginx/hello.conf:/etc/nginx/conf.d/hello.conf",
          "local/www:/www/data"
        ]
      }

      template {
        data        = <<EOF
server {
  root /www/data;
  listen {{ env "NOMAD_PORT_http" }};
}
EOF
        destination = "local/nginx/hello.conf"
      }

      template {
        data        = file("./index.html")
        destination = "local/www/index.html"
      }
    }
  }
}
```

#### `index.html`
```html
<html>
  <head>
    <title>Hello, World!</title>
  </head>
  <body>
    <p>Hello, World!</p>
  </body>
</html>
```

### Expected Behavior
The `nginx` job is created with the index page content read from `index.html`.

### Actual Behavior
```shellsession
$ terraform plan

nomad_job.nginx: Refreshing state... [id=nginx]

Error: error parsing jobspec: job "nginx" {
  datacenters = ["dc1"]

  group "nginx" {
    network {
      port "http" {
        to     = 8080
        static = 8080
      }
    }

    task "nginx" {
      driver = "docker"

      config {
        image = "nginx:1.19"
        ports = ["http"]
        volumes = [
          "local/nginx/hello.conf:/etc/nginx/conf.d/hello.conf",
          "local/www:/www/data"
        ]
      }

      template {
        data        = <<EOF
server {
  root /www/data;
  listen {{ env "NOMAD_PORT_http" }};
}
EOF
        destination = "local/nginx/hello.conf"
      }

      template {
        data        = file("./index.html")
        destination = "local/www/index.html"
      }
    }
  }
}
:35,23-28: Error in function call; Call to function "file" failed: filesystem function disabled.
job "nginx" {
  datacenters = ["dc1"]

  group "nginx" {
    network {
      port "http" {
        to     = 8080
        static = 8080
      }
    }

    task "nginx" {
      driver = "docker"

      config {
        image = "nginx:1.19"
        ports = ["http"]
        volumes = [
          "local/nginx/hello.conf:/etc/nginx/conf.d/hello.conf",
          "local/www:/www/data"
        ]
      }

      template {
        data        = <<EOF
server {
  root /www/data;
  listen {{ env "NOMAD_PORT_http" }};
}
EOF
        destination = "local/nginx/hello.conf"
      }

      template {
        data        = file("./index.html")
        destination = "local/www/index.html"
      }
    }
  }
}
:35,23-28: Unsuitable value type; Unsuitable value: value must be known

  on main.tf line 14, in resource "nomad_job" "nginx":
  14: resource "nomad_job" "nginx" {
```

### Steps to Reproduce
1. `terraform plan`

### References
- GH-179

### PR DESCRIPTION
**Pull request by lgfa29**
Using filesystem functions in a jobspec will create an implicit dependency in Terraform, which means that changes to the external file will not be detected in the next `terraform plan`.

To avoid this type of confusion, filesystem functions are disabled by default when using HCL2 parsing, and must be explicitly enabled in the Terraform configuration:

```hcl
resource "nomad_job" "nginx" {
  jobspec = file("${path.module}/nginx.nomad")
  hcl2 {
    enabled  = true
    allow_fs = true
  }
}
```

The `hcl2` parameter has also been converted from a boolean to a block in order to hold more configuration options.

Relevant docs change:
image

Closes #191.

### CODE REVIEW

**Review by cgbaker — APPROVED** [review]
Hello!

**Review by jrasell — DISMISSED** [review]
is it me you're looking for?

**Review by jrasell — APPROVED** [review]
I can see it in your eyes

**Comment by cgbaker** [comment]
this is all i've ever wanted.

**Pull request merged**
